#!/bin/bash

#PBS -d /stornext/snfs2/1000GENOMES/DATA2/CAfGEN/
#PBS -o /stornext/snfs2/1000GENOMES/DATA2/CAfGEN/Log
#PBS -q analysis
#PBS -A proj-fy0007
#PBS -V
#PBS -j oe
#PBS -N sam2bam
#PBS -l nodes=1:ppn=2,mem=16G
#PBS -t 2-95

increment=1
istart=$[(PBS_ARRAYID-1)*increment+1]
iend=$[PBS_ARRAYID*increment]

list=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bam2/sam.list
indir=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bam2
outdir=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bam2/batch2_bam
mkdir -p $outdir

for line in $(awk 'NR>='$istart' && NR<='$iend'' $list); do
    basename=$(echo $line | cut -d\. -f1)
    command="samtools view -b $indir/$basename.sam > $outdir/$basename.bam"
    echo $command
    samtools view -b $indir/$basename.sam > $outdir/$basename.bam

done

echo "ALL DONE!"
