#!/bin/bash

#PBS -d /stornext/snfs2/1000GENOMES/DATA2/CAfGEN
#PBS -o /stornext/snfs2/1000GENOMES/DATA2/CAfGEN/Log
#PBS -q analysis
#PBS -A proj-fy0007
#PBS -V
#PBS -j oe
#PBS -N sortbam_trim_m20
#PBS -l nodes=1:ppn=1,mem=6G
#PBS -t 2-95

increment=1
istart=$[(PBS_ARRAYID-1)*increment+1]
iend=$[PBS_ARRAYID*increment]

list=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bam2_m20/bam.list
java=/hgsc_software/java/current/bin/java
picard=/hgsc_software/picard/picard-tools-1.93/SortSam.jar
bamdir=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bam2_m20
outdir=/stornext/snfs2/1000GENOMES/DATA2/CAfGEN/trimmed_bamsort_m20
mkdir -p $outdir

for line in $(awk 'NR>='$istart' && NR<='$iend'' $list); do
    basename=$(echo $line | cut -d\. -f1)
    bam=${bamdir}/${basename}.bam
    out=${outdir}/${basename}.sorted.bam

    command="$java -jar -Xmx6g -jar $picard I=$bam O=$out SO=coordinate TMP_DIR=$bamdir VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=LENIENT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false"
    echo $command
    $java -jar -Xmx6g -jar $picard I=$bam O=$out SO=coordinate TMP_DIR=$bamdir VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=LENIENT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=5000\
00 CREATE_INDEX=false CREATE_MD5_FILE=false


done
